### ISSUE TITLE
Should "time" be part of the Spec?

### ISSUE THREAD

**Issue by xsb** [xsb/dog#33]
I talk with @slapresta and he thinks that the tool is responsible for this (and for enabling/disabling it), and should not be part of the spec at all. I'm starting to agree, what do you think?

https://github.com/xsb/dog/blob/master/DOGFILE_SPEC.md#time

**Comment by slapresta** [comment]
I don't know if the tool is responsible for this: while I don't find it particularly useful, I can see how something like `dog --time task` is an interesting feature to provide, particularly as it breaks down the time a task took into its sub-steps and hooks.

I do think that it shouldn't be part of the *spec*. I can't find any reason why a task would or wouldn't be marked as "time" on the Dogfile. Why would or wouldn't a task be "timey"? It seems like it's only related to the context in which you run the task, rather than to the task itself.

**Comment by xsb** [comment]
@slapresta I agree, different dogtools will have different requirements and having this in the Spec will make it more difficult. For example a chat bot is not going to measure elapsed time, but a task server (I'm thinking about Rundeck here) will always do it.

I also agree that this is a flag for `dog`, not for a task. If a task have pre/post-hooks, `dog` can measure the time of each task and the total ellapsed time, printing the information at the end.
