### ISSUE TITLE
Be able to call more than 1 task at a time

### ISSUE THREAD

**Issue by marc-gr** [xsb/dog#37]
Maybe would be a good addition to be able to do this:

```
dog task1 task2 task3
```

then task1, task2 and task3 will be executed one after each other.

Maybe we can even allow something like:
```
dog -p task1 task2 task3
```

to execute them in parallel, does this makes any sense?

**Comment by xsb** [comment]
How are we going to manage task parameters if we allow this behaviour? One idea could be:

```
dog task1 --arg1 --arg2 task2 --arg1 --arg2 task3 --arg1 --arg2
```

I like the idea of parallelism (although I can't think of any useful case right now) but I'm not sure about doing it because of a flag. Actually I'm not sure yet about providing flags to dog at all. There is a benefit (simplicity) on only supporting flags and arguments to tasks. But again, I'm not sure yet.

**Comment by slapresta** [comment]
If we want to have flags with arguments *and* multiple execution, the parsing gets a lot harder: not just from a code perspective but also from a human perspective. Is `dog foo --bar --baz quux` to be parsed as `dog (foo --bar --baz) (quux)`, or as `dog (foo --bar --baz quux)`?

**Comment by slapresta** [comment]
We can probably choose to not have this feature, and instead make it easy to define a dog task that just references other dog tasks; you can define i.e. `dog woof` as `dog build run clean`.

**Comment by xsb** [comment]
I'm closing this one.
